services:
  pg:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: delivery_service
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d delivery_service"]
      interval: 5s
      timeout: 3s
      retries: 3
  
  rmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  
  redis:
    image: redis:7-alpine
    # environment:
      # REDIS_PASSWORD=pass
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    
  app:
    build: .
    depends_on:
      pg:
        condition: service_healthy
      redis:
        condition: service_healthy
      rmq:
        condition: service_healthy
    ports:
      - "8001:8001"
    volumes:
      - .:/app

  worker:
    build: .
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    command: poetry run python -u -m src.workers.parcel_worker
    volumes:
      - ./:/app               
    depends_on:
      pg:
        condition: service_healthy
      redis:
        condition: service_healthy
      rmq:
        condition: service_healthy
    

volumes:
  pgdata:
  rabbitmq_data: